import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatINR } from './currency';

export const generateTripSummaryPDF = (tripData, expenses, bookings, itinerary) => {
  const doc = new jsPDF();

  // Color Palette
  const primaryColor = [102, 126, 234]; // #667eea
  const secondaryColor = [45, 55, 72]; // Dark Gray
  const accentColor = [40, 167, 69]; // Green

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text("Trip Summary", 14, 25);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text("BudgetGo Planner", 160, 25);

  let yPos = 55;

  // Trip Details Section
  doc.setTextColor(...secondaryColor);
  doc.setFontSize(18);
  doc.text(tripData.tripName || "My Trip", 14, yPos);

  yPos += 10;
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Destination: ${tripData.destination}`, 14, yPos);
  doc.text(`Duration: ${tripData.duration}`, 14, yPos + 6);
  doc.text(`Travelers: ${tripData.travelers}`, 14, yPos + 12);

  // Right side stats
  doc.setFontSize(14);
  doc.setTextColor(...accentColor);
  doc.text(`Total Budget: ${formatINR(tripData.budget)}`, 140, yPos);

  const totalSpent = tripData.totalSpent || 0;
  const remaining = tripData.budget - totalSpent;

  doc.setTextColor(totalSpent > tripData.budget ? 220 : 100, 53, 69);
  doc.text(`Spent: ${formatINR(totalSpent)}`, 140, yPos + 8);

  doc.setTextColor(remaining < 0 ? 220 : 40, remaining < 0 ? 53 : 167, remaining < 0 ? 69 : 69);
  doc.text(`Remaining: ${formatINR(remaining)}`, 140, yPos + 16);

  yPos += 30;

  // Expenses Table
  doc.setFontSize(16);
  doc.setTextColor(...primaryColor);
  doc.text("Expense Breakdown", 14, yPos);

  yPos += 5;

  const expenseRows = expenses.map(exp => [
    exp.title || exp.category,
    exp.category,
    new Date(exp.date).toLocaleDateString(),
    formatINR(exp.amount)
  ]);

  doc.autoTable({
    startY: yPos,
    head: [['Description', 'Category', 'Date', 'Amount']],
    body: expenseRows,
    theme: 'grid',
    headStyles: { fillColor: primaryColor },
    styles: { fontSize: 10 },
    foot: [['TOTAL', '', '', formatINR(totalSpent)]],
    footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' }
  });

  yPos = doc.lastAutoTable.finalY + 20;

  // Bookings Section
  if (bookings && bookings.length > 0) {
    doc.setFontSize(16);
    doc.setTextColor(...primaryColor);
    doc.text("Bookings", 14, yPos);
    yPos += 5;

    const bookingRows = bookings.map(b => [
      b.type,
      b.name,
      b.status,
      formatINR(b.price || 0)
    ]);

    doc.autoTable({
      startY: yPos,
      head: [['Type', 'Provider', 'Status', 'Cost']],
      body: bookingRows,
      theme: 'striped',
      headStyles: { fillColor: [40, 167, 69] }
    });

    yPos = doc.lastAutoTable.finalY + 20;
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    doc.text(`Generated by BudgetGo on ${new Date().toLocaleDateString()}`, 105, 295, { align: 'center' });
  }

  doc.save(`${tripData.tripName || 'Trip'}_Summary.pdf`);
};
