spring.application.name=budgetgo-backend
server.port=4001

# --- Database (configure for MySQL) ---
spring.datasource.url=jdbc:mysql://localhost:3306/budgetgo
spring.datasource.username=root
spring.datasource.password=Karneyal@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Disable SQL init by default
spring.sql.init.mode=never

# Frontend URL for invitation links
app.frontend.url=http://localhost:3000cd

# --- Razorpay Configuration ---
razorpay.key.id=rzp_test_YOUR_KEY_HERE
razorpay.key.secret=YOUR_SECRET_HERE

# --- Google OAuth2 Configuration ---
spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET
spring.security.oauth2.client.registration.google.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# AI Configuration
gemini.api.key=YOUR_GEMINI_API_KEY


# --- Email Configuration (Gmail) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=budgetgo3@gmail.com
spring.mail.password=cufhjjnxwnluofzq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
